load("//bazel:test.bzl", "redpanda_cc_bench", "redpanda_cc_gtest")

redpanda_cc_gtest(
    name = "leveling_queue_test",
    timeout = "short",
    srcs = ["leveling_queue_test.cc"],
    cpu = 1,
    deps = [
        "//src/v/cloud_topics/level_one/maintenance:meta",
        "//src/v/cloud_topics/level_one/maintenance/leveling:leveling_queue",
        "//src/v/cloud_topics/level_one/metastore",
        "//src/v/model",
        "//src/v/test_utils:gtest",
        "@googletest//:gtest",
        "@seastar",
    ],
)

redpanda_cc_bench(
    name = "leveling_queue_rpbench",
    timeout = "short",
    srcs = ["leveling_queue_bench.cc"],
    deps = [
        "//src/v/cloud_topics/level_one/maintenance:meta",
        "//src/v/cloud_topics/level_one/maintenance/leveling:leveling_queue",
        "//src/v/cloud_topics/level_one/metastore",
        "//src/v/container:chunked_vector",
        "//src/v/model",
        "//src/v/random:generators",
        "@seastar",
        "@seastar//:benchmark",
    ],
)

redpanda_cc_gtest(
    name = "leveling_reducer_test",
    timeout = "short",
    srcs = ["leveling_reducer_test.cc"],
    cpu = 1,
    deps = [
        "//src/v/cloud_topics/level_one/frontend_reader/tests:l1_reader_fixture",
        "//src/v/cloud_topics/level_one/maintenance:meta",
        "//src/v/cloud_topics/level_one/maintenance:worker_probe",
        "//src/v/cloud_topics/level_one/maintenance/leveling:leveling_sink",
        "//src/v/cloud_topics/level_one/maintenance/leveling:leveling_source",
        "//src/v/cloud_topics/level_one/metastore",
        "//src/v/cloud_topics/level_one/metastore:offset_interval_set",
        "//src/v/cloud_topics/level_one/metastore:simple",
        "//src/v/compaction:reducer",
        "//src/v/config",
        "//src/v/container:chunked_vector",
        "//src/v/model",
        "//src/v/model/tests:random",
        "//src/v/test_utils:gtest",
        "//src/v/utils:prefix_logger",
        "@googletest//:gtest",
        "@seastar",
    ],
)
