/*
 * Copyright 2025 Redpanda Data, Inc.
 *
 * Licensed as a Redpanda Enterprise file under the Redpanda Community
 * License (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * https://github.com/redpanda-data/redpanda/blob/master/licenses/rcl.md
 */

#pragma once

#include "cloud_topics/level_one/common/file_io.h"
#include "cloud_topics/level_one/frontend_reader/level_one_reader_probe.h"
#include "cloud_topics/level_one/maintenance/compaction/compaction_queue.h"
#include "cloud_topics/level_one/maintenance/leveling/leveling_queue.h"
#include "cloud_topics/level_one/maintenance/log_collector.h"
#include "cloud_topics/level_one/maintenance/log_info_collector.h"
#include "cloud_topics/level_one/maintenance/meta.h"
#include "cloud_topics/level_one/maintenance/scheduler_probe.h"
#include "cloud_topics/level_one/maintenance/scheduling_policies.h"
#include "cloud_topics/level_one/maintenance/worker_manager.h"
#include "cloud_topics/level_one/metastore/replicated_metastore.h"
#include "config/property.h"
#include "model/fundamental.h"
#include "ssx/semaphore.h"
#include "ssx/work_queue.h"

class SchedulerTestFixture;

namespace cloud_topics::l1 {

/*
 * The `compaction_scheduler` contains all of the relevant objects required for
 * cloud topics compaction. It exists on shard0 and manages:
 *  - A `log_collector`, which pushes logs this broker is responsible for
 * compacting to both a set and intrusive list of logs.
 * - A `log_info_collector` which fetches metadata for managed logs from the
 * metastore on a sampling interval in the main `compaction_scheduling_loop()`.
 * - A `log_compaction_queue` which is populated with shared pointers to managed
 * logs that require compaction, sorted by a heuristic provided by the
 * `scheduling_policy`.
 * - A `worker_manager` which manages a `compaction_worker` on each shard,
 * which individually pull compaction work from the `log_compaction_queue` on
 * shard0. Compaction updates generated by workers are pushed to the
 * `metastore` and cloud storage via multipart uploads. Workers are alerted of
 * new work on the same sampling interval in `compaction_scheduling_loop()`.
 */
class compaction_scheduler {
public:
    compaction_scheduler(
      compaction_cluster_state,
      ss::sharded<file_io>*,
      ss::sharded<l1::replicated_metastore>*,
      ss::sharded<level_one_reader_probe>*);

    // Starts the contained `_log_collector`, `_worker_manager`, and the
    // backgrounded scheduling loop.
    ss::future<> start();

    // Shuts down concurrency primitives, thereby stopping the backgrounded
    // scheduling loop, stops the `_log_collector`, requests inflight compaction
    // jobs in the `_worker_manager` be stopped, drains the managed partition
    // log list, and finally shuts down the `_worker_manager` once it is safe to
    // do so.
    ss::future<> stop();

    // Returns `true` iff the provided `tidp` is managed by this scheduler.
    bool is_managed(const model::ntp&) const noexcept;

    // Pushes a new `tidp` to be managed by this scheduler to the list of
    // `tidp`s. It is the caller's responsibility to ensure the partition is
    // not already managed by this scheduler.
    void manage_partition(
      const model::ntp&, const model::topic_id_partition&, std::string_view);

    // Removes the `tidp` from the list of managed partitions. No-ops if the
    // provided `tidp` is not managed by this scheduler. Because the `tidp`
    // may be undergoing an inflight compaction, an early stop is requested by
    // the `_worker_manager`.
    void unmanage_partition(const model::ntp&, std::string_view);

private:
    // Registers binding watches that drive disabling/enabling maintenance
    // fibers by submitting start/stop jobs to `_scheduler_update_queue`.
    void watch_config_changes();

    // The compaction scheduling loop.
    ss::future<> compaction_scheduling_loop();

    // The leveling scheduling loop.
    ss::future<> leveling_scheduling_loop();

    // A single scheduling iteration called from above loops.
    ss::future<> do_compaction_scheduling();
    ss::future<> do_leveling_scheduling();

    // True iff the corresponding loop should keep running: the gate is open,
    // the scheduler-wide abort has not fired, and the loop's target state is
    // `active`.
    bool should_run_compaction_loop() const;
    bool should_run_leveling_loop() const;

    // Sets `_*_target_loop_state = active` and drives the loop toward it:
    // launches the background maintenance fiber, assigning a value to
    // `_*_loop_fut` while resuming underlying workers. No-ops once the
    // scheduler is shutting down.
    ss::future<> resume_compaction_loop();
    ss::future<> resume_leveling_loop();

    // Sets `_*_target_loop_state = paused` and drives the loop toward it:
    // tears down the background maintenance fiber, clearing `_*_loop_fut`
    // while pausing underlying workers. No-ops once the scheduler is shutting
    // down.
    ss::future<> pause_compaction_loop();
    ss::future<> pause_leveling_loop();

    // Join a loop's fiber and clear its future (no-op if not running). Mirrors
    // the per-shard worker's `clear_*_work_fut`.
    ss::future<> clear_compaction_loop_fut();
    ss::future<> clear_leveling_loop_fut();

private:
    // Pointer to sharded `file_io` held by `app`. Used by the `worker_manager`
    // for reading L1 objects and writing compacted objects to cloud storage.
    ss::sharded<file_io>* _io;

    // Pointer to metastore.
    ss::sharded<replicated_metastore>* _metastore;

private:
    // Responsible for pushing logs to manage/unmanage to this scheduler.
    std::unique_ptr<log_collector> _log_collector;

    // Responsible for collecting compaction metadata (see: `log_info` in
    // `meta.h`) for managed logs during a scheduling loop.
    log_info_collector _log_info_collector;

    // Responsible for sorting logs collected by info_collector for compaction.
    std::unique_ptr<scheduling_policy> _scheduling_policy;

    // Responsible for dispatching compaction jobs to per-shard workers.
    worker_manager _worker_manager;

    // The interval on which compaction loop is executed.
    config::binding<std::chrono::milliseconds> _compaction_interval;

    // The interval on which the leveling loop is executed.
    config::binding<std::chrono::milliseconds> _leveling_interval;

    config::binding<bool> _compaction_disabled;
    config::binding<bool> _leveling_disabled;

    // This semaphore is used as a way to signal a change to
    // `cloud_topics_compaction_interval_ms` during the `wait()` operation in
    // the compaction scheduling loop.
    ssx::semaphore _compaction_sem{0, "cloud_topics::scheduler::compaction"};

    // Used to signal a change to `cloud_topics_leveling_interval_ms` during
    // the `wait()` operation in the leveling scheduling loop.
    ssx::semaphore _leveling_sem{0, "cloud_topics::scheduler::leveling"};

    ss::abort_source _as;
    ss::gate _gate;

    // Set of logs this scheduler is responsible for issuing compaction jobs
    // for.
    log_set_t _logs;

    // Intrusive list of logs this scheduler is responsible for issuing
    // compaction jobs for.
    log_list_t _logs_list;

    // Jobs for logs in `_logs/_logs_list` that have a sampled metastore info
    // and are eligible for compaction, ordered by the scheduling policy.
    compaction_queue _compaction_queue;

    // Leveling jobs (one per levelable_range) ready to be picked up by the
    // leveling fiber on any worker shard, ordered by expected extent
    // reclamation.
    leveling_queue _leveling_queue;

    // Linearizes enable/disable transitions of the scheduling loops so that a
    // rapid disable/enable can't race the asynchronous teardown of a loop.
    ssx::work_queue _scheduler_update_queue;

    // Per-loop *target* lifecycle state: what we want the loop to become, not
    // what it currently is. Each linearized transition task records the new
    // desire here as its first act and then drives the loop toward it; the
    // loop's fiber keeps running only while the target remains `active`. The
    // actual state is derived: the fiber is up iff `_*_loop_fut` is engaged.
    // * `active`: the loop should be running and scheduling work.
    // * `paused`: disabled via the disablement configs. The fiber is torn
    //    down (`_loop_fut == std::nullopt`) until re-enabled.
    // * `stopped`: the scheduler is shutting down; terminal.
    enum class loop_state { active, paused, stopped };
    loop_state _compaction_target_loop_state{loop_state::paused};
    loop_state _leveling_target_loop_state{loop_state::paused};

    // The scheduling-loop fibers, if running.
    std::optional<ss::future<>> _compaction_loop_fut;
    std::optional<ss::future<>> _leveling_loop_fut;

    // TODO: remove this once more cluster objects speak `topic_id_partition`.
    chunked_hash_map<model::ntp, model::topic_id_partition> _ntp_to_tidp;

private:
    compaction_scheduler_probe _probe;

    friend class ::SchedulerTestFixture;

    // Testing c-tor
    compaction_scheduler(log_info_collector);
};

} // namespace cloud_topics::l1
